/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimilarityRouteImport } from './routes/similarity'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DiversionRouteImport } from './routes/diversion'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CommandRouteImport } from './routes/command'
import { Route as IndexRouteImport } from './routes/index'

const SimilarityRoute = SimilarityRouteImport.update({
  id: '/similarity',
  path: '/similarity',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DiversionRoute = DiversionRouteImport.update({
  id: '/diversion',
  path: '/diversion',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/demo': typeof DemoRoute
  '/diversion': typeof DiversionRoute
  '/forecast': typeof ForecastRoute
  '/learning': typeof LearningRoute
  '/resources': typeof ResourcesRoute
  '/sandbox': typeof SandboxRoute
  '/similarity': typeof SimilarityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/demo': typeof DemoRoute
  '/diversion': typeof DiversionRoute
  '/forecast': typeof ForecastRoute
  '/learning': typeof LearningRoute
  '/resources': typeof ResourcesRoute
  '/sandbox': typeof SandboxRoute
  '/similarity': typeof SimilarityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/demo': typeof DemoRoute
  '/diversion': typeof DiversionRoute
  '/forecast': typeof ForecastRoute
  '/learning': typeof LearningRoute
  '/resources': typeof ResourcesRoute
  '/sandbox': typeof SandboxRoute
  '/similarity': typeof SimilarityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command'
    | '/demo'
    | '/diversion'
    | '/forecast'
    | '/learning'
    | '/resources'
    | '/sandbox'
    | '/similarity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command'
    | '/demo'
    | '/diversion'
    | '/forecast'
    | '/learning'
    | '/resources'
    | '/sandbox'
    | '/similarity'
  id:
    | '__root__'
    | '/'
    | '/command'
    | '/demo'
    | '/diversion'
    | '/forecast'
    | '/learning'
    | '/resources'
    | '/sandbox'
    | '/similarity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandRoute: typeof CommandRoute
  DemoRoute: typeof DemoRoute
  DiversionRoute: typeof DiversionRoute
  ForecastRoute: typeof ForecastRoute
  LearningRoute: typeof LearningRoute
  ResourcesRoute: typeof ResourcesRoute
  SandboxRoute: typeof SandboxRoute
  SimilarityRoute: typeof SimilarityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/similarity': {
      id: '/similarity'
      path: '/similarity'
      fullPath: '/similarity'
      preLoaderRoute: typeof SimilarityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diversion': {
      id: '/diversion'
      path: '/diversion'
      fullPath: '/diversion'
      preLoaderRoute: typeof DiversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandRoute: CommandRoute,
  DemoRoute: DemoRoute,
  DiversionRoute: DiversionRoute,
  ForecastRoute: ForecastRoute,
  LearningRoute: LearningRoute,
  ResourcesRoute: ResourcesRoute,
  SandboxRoute: SandboxRoute,
  SimilarityRoute: SimilarityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
